### ISSUE TITLE
Make S3 script generic

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#18]
The S3 script needs to be more generic, maybe we can use some shell blackmagic.
At least the filenames should be variables.

These variables should be used in the Gruntfile and Jekyll config, too.

**Comment by davidpfahler** [comment]
Fair point. But even better than using variables, the best method would be to just sync the entire folder to s3. That is possible, but I didn't to it at first, because I didn't want all files in the build folder to be on s3 (e.g. the html files). If we just separated them, we could simply sync the entire folder.
