### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/website#9]
When is the time to embed them? After the fifth article? The third? Don't know. What do you think @davidpfahler

**Comment by boennemann** [comment]
@davidpfahler ??

**Comment by davidpfahler** [comment]
If I remember Alexej correctly, he suggests not adding analytics before you are ranking. 1. What does "ranking" mean? I guess he means on the first page? 2. What are we trying to rank for (keyword research)? @boennemann, you have suggested to do this backwards; writing content and then looking at the keywords we do rank for. I don't quite understand yet how this would lead to more traffic though. I would just b/c of gut feeling do what Alexej does, because it seems to work. On the other hand, I have no idea about keywords research and would have to dive into it, which I have no time for. But it seems we need to discuss the general strategy before we go into detailed issues about Analytics or comments #8.

**Comment by boennemann** [comment]
2f4580267bf431e4928d8377a32b1056ba7b6194
